"""fix_security_question_typo

Revision ID: 43be85bb18fc
Revises: 3de3042fe21f
Create Date: 2026-02-23 07:12:06.269991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '43be85bb18fc'
down_revision: Union[str, Sequence[str], None] = '3de3042fe21f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('security_question', sa.Enum('MOTHERS_MAIDEN_NAME', 'FIRST_PET_NAME', 'FAVORITE_TEACHER', 'BIRTH_CITY', 'FAVORITE_BOOK', name='securityquestionsschema'), nullable=False))
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('user', 'securtiy_question')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('securtiy_question', postgresql.ENUM('MOTHERS_MAIDEN_NAME', 'FIRST_PET_NAME', 'FAVORITE_TEACHER', 'BIRTH_CITY', 'FAVORITE_BOOK', name='securityquestionsschema'), autoincrement=False, nullable=False))
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('user', 'security_question')
    # ### end Alembic commands ###
